# Generated by Django 2.1.3 on 2018-11-26 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_enumfield.db.fields
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('castpage', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', django_enumfield.db.fields.EnumField(default=1, enum=events.models.Role)),
                ('writein', models.CharField(blank=True, max_length=64, verbose_name='Write-In')),
            ],
            options={
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Event Name')),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='castpage.Cast')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='casting',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castings', to='events.Event'),
        ),
        migrations.AddField(
            model_name='casting',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='castings', to='userprofile.Profile'),
        ),
    ]
