# Generated by Django 2.1.3 on 2018-11-22 05:32

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_profile_full_name'),
        ('events', '0002_auto_20181107_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', django_enumfield.db.fields.EnumField(default=1, enum=events.models.Role)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castings', to='events.Event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castings', to='userprofile.Profile')),
            ],
        ),
    ]
