# Generated by Django 2.1.3 on 2018-11-15 04:31

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20181111_2104'),
        ('events', '0002_auto_20181107_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[(events.models.Role('Dr. Frank-N-Furter'), 'Dr. Frank-N-Furter'), (events.models.Role('Janet Weiss'), 'Janet Weiss'), (events.models.Role('Brad Majors'), 'Brad Majors'), (events.models.Role('Riff Raff'), 'Riff Raff'), (events.models.Role('Magenta'), 'Magenta'), (events.models.Role('Columbia'), 'Columbia'), (events.models.Role('Dr. Everett V. Scott'), 'Dr. Everett V. Scott'), (events.models.Role('Rocky Horror'), 'Rocky Horror'), (events.models.Role('Eddie'), 'Eddie'), (events.models.Role('The Criminologist'), 'The Criminologist'), (events.models.Role('Transylvanian'), 'Transylvanian'), (events.models.Role('Emcee'), 'Emcee'), (events.models.Role('Trixie'), 'Trixie'), (events.models.Role('Tech'), 'Tech'), (events.models.Role('Lights'), 'Lights'), (events.models.Role('Photographer'), 'Photographer')], max_length=8)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castings', to='events.Event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castings', to='userprofile.Profile')),
            ],
        ),
    ]
