# Generated by Django 2.1.3 on 2018-11-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_casting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casting',
            options={'ordering': ['role']},
        ),
        migrations.AddField(
            model_name='casting',
            name='writein',
            field=models.CharField(blank=True, max_length=64, verbose_name='Write-In'),
        ),
        migrations.AlterField(
            model_name='casting',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='castings', to='userprofile.Profile'),
        ),
    ]
