# Generated by Django 2.1.3 on 2018-11-26 20:43

import castpage.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Cast Name')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', tinymce.models.HTMLField(verbose_name='About Us')),
                ('logo', sorl.thumbnail.fields.ImageField(blank=True, upload_to=castpage.models.cast_logo, verbose_name='Cast Logo')),
                ('email', models.EmailField(max_length=128, verbose_name='Contact Email')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('external_url', models.URLField(blank=True, verbose_name='Existing Homepage')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook Group URL')),
                ('twitter_user', models.CharField(blank=True, max_length=15, verbose_name='Twitter Username')),
                ('instagram_user', models.CharField(blank=True, max_length=30, verbose_name='Instagram Username')),
                ('blocked', models.ManyToManyField(related_name='blocked_casts', to='userprofile.Profile')),
                ('managers', models.ManyToManyField(related_name='managed_casts', to='userprofile.Profile')),
                ('member_requests', models.ManyToManyField(related_name='requested_casts', to='userprofile.Profile')),
                ('members', models.ManyToManyField(related_name='member_casts', to='userprofile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Section Title')),
                ('text', tinymce.models.HTMLField(verbose_name='Content')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Section Priority')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_sections', to='castpage.Cast')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=castpage.models.cast_photo)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='castpage.Cast')),
            ],
            options={
                'ordering': ['-pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KVStore',
            fields=[
                ('key', models.CharField(serialize=False,
                                         db_column='key',
                                         max_length=200,
                                         primary_key=True)),
                ('value', models.TextField()),
            ],
        ),
    ]
