# Generated by Django 2.1.1 on 2018-09-16 20:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('castpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='cast',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cast',
            name='external_url',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cast',
            name='facebook_url',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='cast',
            name='instagram_user',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='cast',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='twitter_user',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='cast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_sections', to='castpage.Cast'),
        ),
    ]
