# Generated by Django 2.1.1 on 2018-10-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castpage', '0003_auto_20180918_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='managers',
            field=models.ManyToManyField(related_name='managed_casts', to='userprofile.Profile'),
        ),
    ]
