# Generated by Django 2.1.1 on 2018-10-04 21:43

import castpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castpage', '0004_auto_20181002_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='logo',
            field=models.ImageField(blank=True, default='../blank_logo.jpg', upload_to=castpage.models.cast_logo),
        ),
    ]
