# Generated by Django 2.1.2 on 2018-10-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castpage', '0005_auto_20181004_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagesection',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='pagesection',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
