# Generated by Django 2.1.2 on 2018-10-16 03:40

import castpage.models
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('castpage', '0006_auto_20181015_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='KVStore',
            fields=[
                ('key', models.CharField(serialize=False,
                                         db_column='key',
                                         max_length=200,
                                         primary_key=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='cast',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='../blank_logo.jpg', upload_to=castpage.models.cast_logo),
        ),
    ]
