# Generated by Django 2.1.2 on 2018-10-25 04:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('castpage', '0007_auto_20181016_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
