# Generated by Django 2.1.2 on 2018-10-26 04:48

import castpage.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('castpage', '0008_auto_20181025_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=castpage.models.cast_logo),
        ),
    ]
