# Generated by Django 2.1.3 on 2018-11-07 03:12

import castpage.models
from django.db import migrations, models
import sorl.thumbnail.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('castpage', '0009_auto_20181026_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='email',
            field=models.EmailField(default='dne@test.com', max_length=128, verbose_name='Contact Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cast',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='About Us'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='external_url',
            field=models.URLField(blank=True, default=None, verbose_name='Existing Homepage'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='facebook_url',
            field=models.URLField(blank=True, default=None, verbose_name='Facebook Group URL'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='instagram_user',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Instagram Username'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=castpage.models.cast_logo, verbose_name='Cast Logo'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Cast Name'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='twitter_user',
            field=models.CharField(blank=True, default=None, max_length=15, verbose_name='Twitter Username'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Section Priority'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Section Title'),
        ),
    ]
