# Generated by Django 2.1.3 on 2018-11-09 04:46

import castpage.models
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('castpage', '0010_auto_20181107_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=castpage.models.cast_photo)),
                ('description', models.TextField(blank=True, default=None)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='castpage.Cast')),
            ],
        )
    ]
