# Generated by Django 2.1.3 on 2018-11-11 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('castpage', '0011_auto_20181109_0446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-pk']},
        ),
    ]
