# Generated by Django 2.1.3 on 2018-11-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_profile_full_name'),
        ('castpage', '0013_auto_20181112_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='members',
            field=models.ManyToManyField(related_name='member_casts', to='userprofile.Profile'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='Existing Homepage'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook Group URL'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='instagram_user',
            field=models.CharField(blank=True, max_length=30, verbose_name='Instagram Username'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='twitter_user',
            field=models.CharField(blank=True, max_length=15, verbose_name='Twitter Username'),
        ),
    ]
