# Generated by Django 2.1.3 on 2018-11-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_profile_full_name'),
        ('castpage', '0014_auto_20181116_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='blocked',
            field=models.ManyToManyField(related_name='blocked_casts', to='userprofile.Profile'),
        ),
        migrations.AddField(
            model_name='cast',
            name='member_requests',
            field=models.ManyToManyField(related_name='requested_casts', to='userprofile.Profile'),
        ),
    ]
