"""empty message

Revision ID: 6e59c09f830d
Revises: 4928a1a79a79
Create Date: 2018-02-10 14:14:40.815203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e59c09f830d'
down_revision = '4928a1a79a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cast', sa.Column('url', sa.String(length=128), nullable=True))
    op.add_column('cast', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cast', 'venue', ['venue_id'], ['id'])
    op.add_column('venue', sa.Column('city', sa.String(length=128), nullable=True))
    op.drop_index('idx_venue_geom', table_name='venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_venue_geom', 'venue', ['geom'], unique=False)
    op.drop_column('venue', 'city')
    op.drop_constraint(None, 'cast', type_='foreignkey')
    op.drop_column('cast', 'venue_id')
    op.drop_column('cast', 'url')
    # ### end Alembic commands ###
