# Generated by Django 2.1.3 on 2018-11-11 03:43

import castpage.models
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=castpage.models.cast_photo)),
                ('description', models.TextField(blank=True, default=None)),
            ],
            options={
                'ordering': ['-pk'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='alt',
            field=models.CharField(blank=True, max_length=128, verbose_name='Stage Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=userprofile.models.profile_image, verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Public Bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userphoto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='userprofile.Profile'),
        ),
    ]
