# Generated by Django 2.1.3 on 2018-11-11 21:04

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20181111_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=userprofile.models.user_photo)),
            ],
            options={
                'ordering': ['-pk'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='userphoto',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='Personal Website'),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook Page'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_user',
            field=models.CharField(blank=True, max_length=30, verbose_name='Instagram Username'),
        ),
        migrations.AddField(
            model_name='profile',
            name='searchable',
            field=models.BooleanField(default=True, verbose_name='Searchable Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='Show Email on Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_user',
            field=models.CharField(blank=True, max_length=15, verbose_name='Twitter Username'),
        ),
        migrations.DeleteModel(
            name='UserPhoto',
        ),
        migrations.AddField(
            model_name='photo',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='userprofile.Profile'),
        ),
    ]
